"""Blind listening page for the dictionary check (voice-data/ckkw-unseen-10.json, generated by tk_ckkw_ali.py --unseen):
each new sentence in Ali's voice twice, as written (raw) and after the dictionary (dict), under letters أ/ب drawn per
sentence and fixed for the session (voice-src/ck-kw-ali/unseen/page-key.json). Rated separately: wrong words (tap them),
Kuwaiti dialect, rhythm and natural tone, then which is better. A sentence the dictionary did not change is left out.
3 sentences a page. Output: voice-src/ck-kw-ali/unseen/page/.  Run: python3 build_unseen_page.py"""
import json
import random
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "voice-src/ck-kw-ali/unseen"
OUT = SRC / "page"
(OUT / "audio").mkdir(parents=True, exist_ok=True)
TEXTS = json.loads((SRC / "texts.json").read_text())
KEYF = SRC / "page-key.json"
key = json.loads(KEYF.read_text()) if KEYF.exists() else {}
rnd = random.SystemRandom()
DIAL = [["kw", "كويتية"], ["near", "قريبة"], ["no", "مو كويتية"]]
FLOW = [["natural", "طبيعي"], ["ok", "مقبول"], ["robotic", "آلي / مو طبيعي"]]
cards, skipped = [], []
for sid, t in TEXTS.items():
    if t["raw"] == t["dict"]:
        skipped.append(sid)
        continue
    key.setdefault(sid, rnd.choice([["raw", "dict"], ["dict", "raw"]]))
    players = []
    for letter, ver in zip("أب", key[sid]):
        name = f"{sid}-{'a' if letter == 'أ' else 'b'}.mp3"
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", str(SRC / f"clone-{sid}-{ver}.wav"), "-ac", "1", "-b:a", "96k", str(OUT / "audio" / name)], check=True)
        players.append({"label": letter, "src": f"audio/{name}"})
    qs = []
    for k, letter in (("a", "أ"), ("b", "ب")):
        qs += [{"key": f"dial_{k}", "label": f"لهجة {letter}؟", "options": DIAL},
               {"key": f"flow_{k}", "label": f"الإيقاع والنبرة في {letter}؟", "options": FLOW}]
    qs.append({"key": "better", "label": "أيهم أحسن بشكل عام؟", "options": [["A", "أ"], ["B", "ب"], ["same", "نفس الشي"]]})
    cards.append({"id": sid, "title": f"جملة {len(cards) + 1}", "text": t["raw"], "players": players, "questions": qs,
                  "words": [{"key": "wrong_a", "label": "في أ: اضغط على أي كلمة انقالت غلط أو مو كويتية"},
                            {"key": "wrong_b", "label": "في ب: اضغط على أي كلمة انقالت غلط أو مو كويتية"}]})
for n, c in enumerate(cards):
    c["part"] = n // 3 + 1
KEYF.write_text(json.dumps(key, ensure_ascii=False))
page = (Path(__file__).parent / "listen-template.html").read_text()
page = page.replace("__TITLE__", "جمل جديدة").replace("__KEY__", "tk-ckkw-unseen").replace(
    "__LEDE__", "كل جملة بصوت علي بنسختين، أ و ب. قيّم كل نسخة لحالها: الكلمات الغلط، اللهجة، والإيقاع والنبرة. بعدين قول أيهم أحسن. "
                f"{cards[-1]['part'] if cards else 0} صفحات، كل صفحة 3 جمل.")
(OUT / "index.html").write_text(page.replace("__CARDS__", json.dumps(cards, ensure_ascii=False)))
print(len(cards), "cards; unchanged (left out):", skipped, "->", OUT)
